# From http://www.irs.gov/file_source/pub/irs-soi/eobk13.doc

#Ruby thinks some leading zeros denote octal so turn the keys into strings

# Subsection codes
SUBSECTION_CODES = Hash.new
     SUBSECTION_CODES[['01','1']]="Government Instrumentality"
     SUBSECTION_CODES[['02','1']]="Title‑Holding Corporation"
     SUBSECTION_CODES[['03','1']]="Charitable Organization"
     SUBSECTION_CODES[['03','2']]="Educational Organization"
     SUBSECTION_CODES[['03','3']]="Literary Organization"
     SUBSECTION_CODES[['03','4']]="Organization to Prevent Cruelty to Animals"
     SUBSECTION_CODES[['03','5']]="Organization to Prevent Cruelty to Children"
     SUBSECTION_CODES[['03','6']]="Organization for Public Safety Testing"
     SUBSECTION_CODES[['03','7']]="Religious Organization"
     SUBSECTION_CODES[['03','8']]="Scientific Organization"
     SUBSECTION_CODES[['04','1']]="Civic League"
     SUBSECTION_CODES[['04','2']]="Local Association of Employees"
     SUBSECTION_CODES[['04','3']]="Social Welfare Organization"
     SUBSECTION_CODES[['05','1']]="Agricultural Organization"
     SUBSECTION_CODES[['05','2']]="Horticultural Organization"
     SUBSECTION_CODES[['05','3']]="Labor Organization"
     SUBSECTION_CODES[['06','1']]="Board of Trade"
     SUBSECTION_CODES[['06','2']]="Business League"
     SUBSECTION_CODES[['06','3']]="Chamber of Commerce"
     SUBSECTION_CODES[['06','4']]="Real Estate Board"
     SUBSECTION_CODES[['07','1']]="Pleasure, Recreational, or Social Club"
     SUBSECTION_CODES[['08','1']]="Fraternal Beneficiary Society, Order or Association"
     SUBSECTION_CODES[['09','1']]="Voluntary Employees' Beneficiary Association (Non-Govt. Emps.)"
     SUBSECTION_CODES[['09','2']]="Voluntary Employees' Beneficiary Association (Govt. Emps.)"
     SUBSECTION_CODES[['10','1']]="Domestic Fraternal Societies and Associations"
     SUBSECTION_CODES[['11','1']]="Teachers Retirement Fund Assoc."
     SUBSECTION_CODES[['12','1']]="Benevolent Life Insurance Assoc."
     SUBSECTION_CODES[['12','2']]="Mutual Ditch or Irrigation Co."
     SUBSECTION_CODES[['12','3']]="Mutual Cooperative Telephone Co."
     SUBSECTION_CODES[['12','4']]="Organization Like Those on Three Preceding Lines"
     SUBSECTION_CODES[['13','1']]="Burial Association"
     SUBSECTION_CODES[['13','2']]="Cemetery Company"
     SUBSECTION_CODES[['14','1']]="Credit Union"
     SUBSECTION_CODES[['14','2']]="Other Mutual Corp. or Assoc."
     SUBSECTION_CODES[['15','1']]="Mutual Insurance Company or Assoc. Other Than Life or Marine"
     SUBSECTION_CODES[['16','1']]="Corp. Financing Crop Operations"
     SUBSECTION_CODES[['17','1']]="Supplemental Unemployment Compensation Trust or Plan"
     SUBSECTION_CODES[['18','1']]="Employee Funded Pension Trust (Created Before 6/25/59)"
     SUBSECTION_CODES[['19','1']]="Post or Organization of War Veterans"
     SUBSECTION_CODES[['20','1']]="Legal Service Organization"
     SUBSECTION_CODES[['21','1']]="Black Lung Trust"
     SUBSECTION_CODES[['22','1']]="Multiemployer Pension Plan"
     SUBSECTION_CODES[['23','1']]="Veterans Assoc. Formed Prior to 1880"
     SUBSECTION_CODES[['24','1']]="Trust Described in Sect. 4049 of ERISA"
     SUBSECTION_CODES[['25','1']]="Title Holding Co. for Pensions, etc."
     SUBSECTION_CODES[['26','1']]="State-Sponsored High Risk Health Insurance Organizations"
     SUBSECTION_CODES[['27','1']]="State-Sponsored Workers' Compensation Reinsurance"
     SUBSECTION_CODES[['29','1']]="ACA 1322 Qualified Nonprofit Health Insurance Issuers"
     SUBSECTION_CODES[['40','1']]="Apostolic and Religious Org. (501(d))"
     SUBSECTION_CODES[['50','1']]="Cooperative Hospital Service Organization (501(e))"
     SUBSECTION_CODES[['60','1']]="Cooperative Service Organization of Operating EducationalOrganization (501(f))"
     SUBSECTION_CODES[['70','1']]="Child Care Organization (501(k))"
     SUBSECTION_CODES[['71','1']]="Charitable Risk Pool"
     SUBSECTION_CODES[['81','1']]="Qualified State-Sponsored Tuition Program "
     SUBSECTION_CODES[['92','1']]="4947(a)(1) - Private Foundation (Form 990PF Filer)"



=begin
From http://www.irs.gov/file_source/pub/irs-soi/eobk13.doc
ACTIVITY CODES

An organization formerly listed up to three activity codes on application Forms 1023 and 1024.  These are codes which reflect an organization's purposes, activities, operations, or type.  From one to three activity codes may be in this field.  Note:  activity codes became obsolete with the adoption of the National Taxonomy of Exempt Entity (NTEE) coding system in January 1995.  However, organizations determined to be exempt prior to that date will reflect the activity codes previously assigned.  

=end

ACTIVITY_CODES = Hash.new

{

#Religious Activities
"001" => {1=>"Religious Activities", 2=>"Church, synagogue, etc"},
"002" => {1=>"Religious Activities", 2=>"Association or convention of churches"},
"003" => {1=>"Religious Activities", 2=>"Religious order"},
"004" => {1=>"Religious Activities", 2=>"Church auxiliary"},
"005" => {1=>"Religious Activities", 2=>"Mission"},
"006" => {1=>"Religious Activities", 2=>"Missionary activities"},
"007" => {1=>"Religious Activities", 2=>"Evangelism"},
"008" => {1=>"Religious Activities", 2=>"Religious publishing activities"},
"029" => {1=>"Religious Activities", 2=>"Other religious activities"},

#Schools, Colleges and Related Activities
"030" => {1=>"Schools, Colleges and Related Activities", 2=>"School, college, trade school, etc."},
"031" => {1=>"Schools, Colleges and Related Activities", 2=>"Special school for the blind, handicapped, etc"},
"032" => {1=>"Schools, Colleges and Related Activities", 2=>"Nursery school"},
"033" => {1=>"Schools, Colleges and Related Activities", 2=>"Faculty group"},
"034" => {1=>"Schools, Colleges and Related Activities", 2=>"Alumni association or group"},
"035" => {1=>"Schools, Colleges and Related Activities", 2=>"Parent or parent‑teachers association"},
"036" => {1=>"Schools, Colleges and Related Activities", 2=>"Fraternity or sorority"},
"037" => {1=>"Schools, Colleges and Related Activities", 2=>"Other student society or group"},
"038" => {1=>"Schools, Colleges and Related Activities", 2=>"School or college athletic association"},
"039" => {1=>"Schools, Colleges and Related Activities", 2=>"Scholarships for children of employees"},
"040" => {1=>"Schools, Colleges and Related Activities", 2=>"Scholarships (other)"},
"041" => {1=>"Schools, Colleges and Related Activities", 2=>"Student loans"},
"042" => {1=>"Schools, Colleges and Related Activities", 2=>"Student housing activities"},
"043" => {1=>"Schools, Colleges and Related Activities", 2=>"Other student aid"},
"044" => {1=>"Schools, Colleges and Related Activities", 2=>"Student exchange with foreign country"},
"045" => {1=>"Schools, Colleges and Related Activities", 2=>"Student operated business"},
"046" => {1=>"Schools, Colleges and Related Activities", 2=>"Private school"},
"059" => {1=>"Schools, Colleges and Related Activities", 2=>"Other school related activities"},

#Cultural, Historical of Other Educational Activities
"060" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Museum, zoo, planetarium, etc."},
"061" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Library"},
"062" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Historical site, records or reenactment"},
"063" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Monument"},
"064" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Commemorative event (centennial, festival, pageant, etc.)"},
"065" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Fair"},
"088" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Community theatrical group"},
"089" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Singing society or group"},
"090" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Cultural performances"},
"091" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Art exhibit"},
"092" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Literary activities"},
"093" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Cultural exchanges with foreign country"},
"094" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Genealogical activities"},
"119" => {1=>"Cultural, Historical of Other Educational Activities", 2=>"Other cultural or historical activities"},

#Other Instructions and Training Activities
"120" => {1=>"Other Instructions and Training Activities", 2=>"Publishing activities"},
"121" => {1=>"Other Instructions and Training Activities", 2=>"Radio or television broadcasting"},
"122" => {1=>"Other Instructions and Training Activities", 2=>"Producing films"},
"123" => {1=>"Other Instructions and Training Activities", 2=>"Discussion groups, forums, panels lectures, etc."},
"124" => {1=>"Other Instructions and Training Activities", 2=>"Study and research (non‑scientific)"},
"125" => {1=>"Other Instructions and Training Activities", 2=>"Giving information or opinion (see also Advocacy)"},
"126" => {1=>"Other Instructions and Training Activities", 2=>"Apprentice training"},
"149" => {1=>"Other Instructions and Training Activities", 2=>"Other instruction and training"},

#Health Services and Related Activities
"150" => {1=>"Health Services and Related Activities", 2=>"Hospital"},
"151" => {1=>"Health Services and Related Activities", 2=>"Hospital auxiliary"},
"152" => {1=>"Health Services and Related Activities", 2=>"Nursing or convalescent home"},
"153" => {1=>"Health Services and Related Activities", 2=>"Care and housing for the aged (see also 382)"},
"154" => {1=>"Health Services and Related Activities", 2=>"Health clinic"},
"155" => {1=>"Health Services and Related Activities", 2=>"Rural medical facility"},
"156" => {1=>"Health Services and Related Activities", 2=>"Blood bank"},
"157" => {1=>"Health Services and Related Activities", 2=>"Cooperative hospital service organization"},
"158" => {1=>"Health Services and Related Activities", 2=>"Rescue and emergency service"},
"159" => {1=>"Health Services and Related Activities", 2=>"Nurses register or bureau"},
"160" => {1=>"Health Services and Related Activities", 2=>"Aid to the handicapped (see also 031)"},
"161" => {1=>"Health Services and Related Activities", 2=>"Scientific research (diseases)"},
"162" => {1=>"Health Services and Related Activities", 2=>"Other medical research"},
"163" => {1=>"Health Services and Related Activities", 2=>"Health insurance (medical, dental, optical, etc.)"},
"164" => {1=>"Health Services and Related Activities", 2=>"Prepared group health plan"},
"165" => {1=>"Health Services and Related Activities", 2=>"Community health planning"},
"166" => {1=>"Health Services and Related Activities", 2=>"Mental health care"},
"167" => {1=>"Health Services and Related Activities", 2=>"Group medical practice association"},
"168" => {1=>"Health Services and Related Activities", 2=>"In‑faculty group practice association"},
"169" => {1=>"Health Services and Related Activities", 2=>"Hospital pharmacy, parking facility, food services, etc."},
"179" => {1=>"Health Services and Related Activities", 2=>"Other health services"},

#Scientific Research Activities
"180" => {1=>"Scientific Research Activities", 2=>"Contact or sponsored scientific research for industry"},
"181" => {1=>"Scientific Research Activities", 2=>"Scientific research for government"},
"199" => {1=>"Scientific Research Activities", 2=>"Other scientific research activities"},

#Business and Professional Organizations
"200" => {1=>"Business and Professional Organizations", 2=>"Business promotion (chamber of commerce, business league, etc."},
"201" => {1=>"Business and Professional Organizations", 2=>"Real estate association"},
"202" => {1=>"Business and Professional Organizations", 2=>"Board of trade"},
"203" => {1=>"Business and Professional Organizations", 2=>"Regulating business"},
"204" => {1=>"Business and Professional Organizations", 2=>"Promotion of fair business practices"},
"205" => {1=>"Business and Professional Organizations", 2=>"Professional association"},
"206" => {1=>"Business and Professional Organizations", 2=>"Professional association auxiliary"},
"207" => {1=>"Business and Professional Organizations", 2=>"Industry trade shows"},
"208" => {1=>"Business and Professional Organizations", 2=>"Convention displays"},
"209" => {1=>"Business and Professional Organizations", 2=>"Research, development and testing"},
"210" => {1=>"Business and Professional Organizations", 2=>"Professional athletic league"},
"211" => {1=>"Business and Professional Organizations", 2=>"Underwriting municipal insurance"},
"212" => {1=>"Business and Professional Organizations", 2=>"Assigned risk insurance activities"},
"213" => {1=>"Business and Professional Organizations", 2=>"Tourist bureau"},
"229" => {1=>"Business and Professional Organizations", 2=>"Other business or professional group"},

#Farming and Related Activities
"230" => {1=>"Farming and Related Activities", 2=>"Farming"},
"231" => {1=>"Farming and Related Activities", 2=>"Farm bureau"},
"232" => {1=>"Farming and Related Activities", 2=>"Agricultural group"},
"233" => {1=>"Farming and Related Activities", 2=>"Horticultural group"},
"234" => {1=>"Farming and Related Activities", 2=>"Farmers cooperative marketing or purchasing"},
"235" => {1=>"Farming and Related Activities", 2=>"Farmers cooperative marketing or purchasing"},
"236" => {1=>"Farming and Related Activities", 2=>"Dairy herd improvement association"},
"237" => {1=>"Farming and Related Activities", 2=>"Breeders association"},
"249" => {1=>"Farming and Related Activities", 2=>"Other farming and related activities"},

#Mutual Organizations
"250" => {1=>"Mutual Organizations", 2=>"Mutual ditch, irrigation, telephone, electric company or like organization"},
"251" => {1=>"Mutual Organizations", 2=>"Credit union"},
"252" => {1=>"Mutual Organizations", 2=>"Reserve funds or insurance for domestic building and loan association, cooperative bank, or mutual savings bank"},
"253" => {1=>"Mutual Organizations", 2=>"Mutual insurance company"},
"254" => {1=>"Mutual Organizations", 2=>"Corporation organized under an Act of Congress (see also use (904)"},
"259" => {1=>"Mutual Organizations", 2=>"Other mutual organization"},

#Employee of Membership Benefit Organizations
"260" => {1=>"Employee of Membership Benefit Organizations", 2=>"Fraternal Beneficiary society, order, or association"},
"261" => {1=>"Employee of Membership Benefit Organizations", 2=>"Improvement of conditions of workers"},
"262" => {1=>"Employee of Membership Benefit Organizations", 2=>"Association of municipal employees"},
"263" => {1=>"Employee of Membership Benefit Organizations", 2=>"Association of employees"},
"264" => {1=>"Employee of Membership Benefit Organizations", 2=>"Employee or member welfare association"},
"265" => {1=>"Employee of Membership Benefit Organizations", 2=>"Sick, accident, death, or similar benefits"},
"266" => {1=>"Employee of Membership Benefit Organizations", 2=>"Strike benefits"},
"267" => {1=>"Employee of Membership Benefit Organizations", 2=>"Unemployment benefits"},
"268" => {1=>"Employee of Membership Benefit Organizations", 2=>"Pension or retirement benefits"},
"269" => {1=>"Employee of Membership Benefit Organizations", 2=>"Vacation benefits"},
"279" => {1=>"Employee of Membership Benefit Organizations", 2=>"Other services or benefits to members or employees"},

#Sports, Athletic Recreational and Social Activities
"280" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Country club"},
"281" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Hobby club"},
"282" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Dinner club"},
"283" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Variety club"},
"284" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Dog club"},
"285" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Women's club"},
"286" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Hunting or fishing club"},
"287" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Swimming or tennis club"},
"288" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Other sports club"},
"296" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Community center"},
"297" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Community recreational facilities (park, playground, etc)"},
"298" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Training in sports"},
"299" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Travel tours"},
"300" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Amateur athletic association"},
"301" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Fundraising athletic or sports event"},
"317" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Other sports or athletic activities"},
"318" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Other recreational activities"},
"319" => {1=>"Sports, Athletic Recreational and Social Activities", 2=>"Other social activities"},

#Youth Activities
"320" => {1=>"Youth Activities", 2=>"Boy Scouts, Girl Scouts, etc."},
"321" => {1=>"Youth Activities", 2=>"Boys Club, Little League, etc."},
"322" => {1=>"Youth Activities", 2=>"FFA, FHA, 4‑H club, etc."},
"323" => {1=>"Youth Activities", 2=>"Key club"},
"324" => {1=>"Youth Activities", 2=>"YMCA, YWCA, YMCA, etc."},
"325" => {1=>"Youth Activities", 2=>"Camp"},
"326" => {1=>"Youth Activities", 2=>"Care and housing of children (orphanage, etc)"},
"327" => {1=>"Youth Activities", 2=>"Prevention of cruelty to children"},
"328" => {1=>"Youth Activities", 2=>"Combat juvenile delinquency"},
"349" => {1=>"Youth Activities", 2=>"Other youth organization or activities"},

#Conservation, Environmental and Beautification Activities
"350" => {1=>"Conservation, Environmental and Beautification Activities", 2=>"Preservation of natural resources (conservation)"},
"351" => {1=>"Conservation, Environmental and Beautification Activities", 2=>"Combating or preventing pollution (air, water, etc)"},
"352" => {1=>"Conservation, Environmental and Beautification Activities", 2=>"Land acquisition for preservation"},
"353" => {1=>"Conservation, Environmental and Beautification Activities", 2=>"Soil or water conservation"},
"354" => {1=>"Conservation, Environmental and Beautification Activities", 2=>"Preservation of scenic beauty"},
"355" => {1=>"Conservation, Environmental and Beautification Activities", 2=>"Wildlife sanctuary or refuge"},
"356" => {1=>"Conservation, Environmental and Beautification Activities", 2=>"Garden club"},
"379" => {1=>"Conservation, Environmental and Beautification Activities", 2=>"Other conservation, environmental or beautification activities"},

#Housing Activities
"380" => {1=>"Housing Activities", 2=>"Low‑income housing"},
"381" => {1=>"Housing Activities", 2=>"Low and moderate income housing"},
"382" => {1=>"Housing Activities", 2=>"Housing for the aged (see also 153)"},
"398" => {1=>"Housing Activities", 2=>"Instruction and guidance on housing"},
"399" => {1=>"Housing Activities", 2=>"Other housing activities"},

#Inner City or Community Activities
"400" => {1=>"Inner City or Community Activities", 2=>"Area development, redevelopment of renewal"},
"401" => {1=>"Inner City or Community Activities", 2=>"Homeowners association"},
"402" => {1=>"Inner City or Community Activities", 2=>"Other activity aimed t combating community deterioration"},
"403" => {1=>"Inner City or Community Activities", 2=>"Attracting new industry or retaining industry in an area"},
"404" => {1=>"Inner City or Community Activities", 2=>"Community promotion"},
"405" => {1=>"Inner City or Community Activities", 2=>"Loans or grants for minority businesses"},
"406" => {1=>"Inner City or Community Activities", 2=>"Crime prevention"},
"407" => {1=>"Inner City or Community Activities", 2=>"Voluntary firemen's organization or auxiliary"},
"408" => {1=>"Inner City or Community Activities", 2=>"Community service organization"},
"429" => {1=>"Inner City or Community Activities", 2=>"Other inner city or community benefit activities"},

#Civil Rights Activities
"430" => {1=>"Civil Rights Activities", 2=>"Defense of human and civil rights"},
"431" => {1=>"Civil Rights Activities", 2=>"Elimination of prejudice and discrimination (race, religion, sex, national origin, etc)"},
"432" => {1=>"Civil Rights Activities", 2=>"Lessen neighborhood tensions"},
"449" => {1=>"Civil Rights Activities", 2=>"Other civil rights activities"},

#Litigation and Legal Aid Activities
"460" => {1=>"Litigation and Legal Aid Activities", 2=>"Public interest litigation activities"},
"461" => {1=>"Litigation and Legal Aid Activities", 2=>"Other litigation or support of litigation"},
"462" => {1=>"Litigation and Legal Aid Activities", 2=>"Legal aid to indigents"},
"463" => {1=>"Litigation and Legal Aid Activities", 2=>"Providing bail"},
"465" => {1=>"Litigation and Legal Aid Activities", 2=>"Plan under IRC section 120"},

#Legislative and Political Activities
"480" => {1=>"Legislative and Political Activities", 2=>"Propose, support, or oppose legislation"},
"481" => {1=>"Legislative and Political Activities", 2=>"Voter information on issues or candidates"},
"482" => {1=>"Legislative and Political Activities", 2=>"Voter education (mechanics of registering, voting etc.)"},
"483" => {1=>"Legislative and Political Activities", 2=>"Support, oppose, or rate political candidates"},
"484" => {1=>"Legislative and Political Activities", 2=>"Provide facilities or services for political campaign activities"},
"509" => {1=>"Legislative and Political Activities", 2=>"Other legislative and political activities"},

#Advocacy Attempt to influence public opinion concerning:
"510" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Firearms control"},
"511" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Selective Service System"},
"512" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"National defense policy"},
"513" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Weapons systems"},
"514" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Government spending"},
"515" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Taxes or tax exemption"},
"516" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Separation of church and state"},
"517" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Government aid to parochial schools"},
"518" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"U.S. foreign policy"},
"519" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"U.S. military involvement"},
"520" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Pacifism and peace"},
"521" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Economic‑political system of U.S."},
"522" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Anti‑communism"},
"523" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Right to work"},
"524" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Zoning or rezoning"},
"525" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Location of highway or transportation system"},
"526" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Rights of criminal defendants"},
"527" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Capital punishment"},
"528" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Stricter law enforcement"},
"529" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Ecology or conservation"},
"530" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Protection of consumer interests"},
"531" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Medical care service"},
"532" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Welfare systems"},
"533" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Urban renewal"},
"534" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Busing student to achieve racial balance"},
"535" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Racial integration"},
"536" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Use of intoxicating beverage"},
"537" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Use of drugs or narcotics"},
"538" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Use of tobacco"},
"539" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Prohibition of erotica"},
"540" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Sex education in public schools"},
"541" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Population control"},
"542" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Birth control methods"},
"543" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Legalized abortion"},
"559" => {1=>"Advocacy Attempt to influence public opinion concerning:", 2=>"Other matters"},

#Other Activities Directed to Individuals
"560" => {1=>"Other Activities Directed to Individuals", 2=>"Supplying money, goods or services to the poor"},
"561" => {1=>"Other Activities Directed to Individuals", 2=>"Gifts or grants to individuals (other than scholarships)"},
"562" => {1=>"Other Activities Directed to Individuals", 2=>"Other loans to individuals"},
"563" => {1=>"Other Activities Directed to Individuals", 2=>"Marriage counseling"},
"564" => {1=>"Other Activities Directed to Individuals", 2=>"Family planning"},
"565" => {1=>"Other Activities Directed to Individuals", 2=>"Credit counseling an assistance"},
"566" => {1=>"Other Activities Directed to Individuals", 2=>"Job training, counseling, or assistance"},
"567" => {1=>"Other Activities Directed to Individuals", 2=>"Draft counseling"},
"568" => {1=>"Other Activities Directed to Individuals", 2=>"Vocational counseling"},
"569" => {1=>"Other Activities Directed to Individuals", 2=>"Referral service (social agencies)"},
"572" => {1=>"Other Activities Directed to Individuals", 2=>"Rehabilitating convicts or ex‑convicts"},
"573" => {1=>"Other Activities Directed to Individuals", 2=>"Rehabilitating alcoholics, drug abusers, compulsive gamblers, etc."},
"574" => {1=>"Other Activities Directed to Individuals", 2=>"Day care center"},
"575" => {1=>"Other Activities Directed to Individuals", 2=>"Services for the aged (see also 153 ad 382)"},

#Activities Purposes and Activities
"600" => {1=>"Activities Purposes and Activities", 2=>"Community Chest, United Way, etc."},
"601" => {1=>"Activities Purposes and Activities", 2=>"Booster club"},
"602" => {1=>"Activities Purposes and Activities", 2=>"Gifts, grants, or loans to other organizations"},
"603" => {1=>"Activities Purposes and Activities", 2=>"Non‑financial services of facilities to other organizations"},

#Other Purposes and Activities
"900" => {1=>"Other Purposes and Activities", 2=>"Cemetery or burial activities"},
"901" => {1=>"Other Purposes and Activities", 2=>"Perpetual (care fund (cemetery, columbarium, etc)"},
"902" => {1=>"Other Purposes and Activities", 2=>"Emergency or disaster aid fund"},
"903" => {1=>"Other Purposes and Activities", 2=>"Community trust or component"},
"904" => {1=>"Other Purposes and Activities", 2=>"Government instrumentality or agency (see also 254)"},
"905" => {1=>"Other Purposes and Activities", 2=>"Testing products for public safety"},
"906" => {1=>"Other Purposes and Activities", 2=>"Consumer interest group"},
"907" => {1=>"Other Purposes and Activities", 2=>"Veterans activities"},
"908" => {1=>"Other Purposes and Activities", 2=>"Patriotic activities"},
"909" => {1=>"Other Purposes and Activities", 2=>"Non-exempt charitable trust described in section 4947(a)(1) of the Code"},
"910" => {1=>"Other Purposes and Activities", 2=>"Domestic organization with activities outside U.S."},
"911" => {1=>"Other Purposes and Activities", 2=>"Foreign organization"},
"912" => {1=>"Other Purposes and Activities", 2=>"Title holding corporation"},
"913" => {1=>"Other Purposes and Activities", 2=>"Prevention of cruelty to animals"},
"914" => {1=>"Other Purposes and Activities", 2=>"Achievement pries of awards"},
"915" => {1=>"Other Purposes and Activities", 2=>"Erection or maintenance of public building or works"},
"916" => {1=>"Other Purposes and Activities", 2=>"Cafeteria, restaurant, snack bar, food services, etc."},
"917" => {1=>"Other Purposes and Activities", 2=>"Thrift ship, retail outlet, etc."},
"918" => {1=>"Other Purposes and Activities", 2=>"Book, gift  or supply store"},
"919" => {1=>"Other Purposes and Activities", 2=>"Advertising"},
"920" => {1=>"Other Purposes and Activities", 2=>"Association of employees"},
"921" => {1=>"Other Purposes and Activities", 2=>"Loans or credit reporting"},
"922" => {1=>"Other Purposes and Activities", 2=>"Endowment fund or financial services"},
"923" => {1=>"Other Purposes and Activities", 2=>"Indians (tribes, cultures, etc.)"},
"924" => {1=>"Other Purposes and Activities", 2=>"Traffic or tariff bureau"},
"925" => {1=>"Other Purposes and Activities", 2=>"Section 501(c)(1) with 50% deductibility"},
"926" => {1=>"Other Purposes and Activities", 2=>"Government instrumentality other than section 501(c)"},
"927" => {1=>"Other Purposes and Activities", 2=>"Fundraising"},
"928" => {1=>"Other Purposes and Activities", 2=>"4947(a)(2) trust"},
"930" => {1=>"Other Purposes and Activities", 2=>"Prepaid legal services pan exempt under IRC section 501(c)(20)"},
"931" => {1=>"Other Purposes and Activities", 2=>"Withdrawal liability payment fund"},
"990" => {1=>"Other Purposes and Activities", 2=>"Section 501(k) child care organization"},
"994" => {1=>"Other Purposes and Activities", 2=>"Described in section 170(b)1)(a)(vi) of the Code"},
"995" => {1=>"Other Purposes and Activities", 2=>"Described in section 509(a)(2) of the Code"},
"998" => {1=>"Other Purposes and Activities", 2=>"Unspecified"}
}
#Activity codes END


=begin
From http://www.irs.gov/file_source/pub/irs-soi/eobk13.doc

National Taxonomy of Exempt Entities (NTEE) Code

The National Taxonomy of Exempt Entities (NTEE) Code is a four digit code used to classify an exempt organization in terms of its primary exempt activity.  A table of the codes found in the first three-digits can be found described below. The first digit (Common Code) is a modifier used to describe activities in support of nonprofit organizations.  The fourth digit further defines the classification of the organization and is not defined here.   

=end
NTEE_COMMON_CODES = Hash.new

{

#Religious Activities
"A" => {1=>"Arts, Culture and Humanities"},
"B" => {1=>"Educational Institutions and Related Activities"},
"C" => {1=>"Environmental Quality, Protection and Beautification "},
"D" => {1=>"Animal-Related"},
"E" => {1=>"Health – General and Rehabilitative"},
"F" => {1=>"Mental Health, Crisis Intervention"},
"G" => {1=>"Diseases, Disorders, Medical Disciplines"},
"H" => {1=>"Medical Research"},
"I" => {1=>"Crime, Legal-Related"},
"J" => {1=>"Employment, Job-Related"},
"K" => {1=>"Food, Agriculture and Nutrition"},
"L" => {1=>"Housing, Shelter"},
"M" => {1=>"Public Safety, Disaster Preparedness and Relief"},
"N" => {1=>"Recreation, Sports, Leisure, Athletics"},
"O" => {1=>"Youth Development"},
"P" => {1=>"Human Services – Multipurpose and Other"},
"Q" => {1=>"International, Foreign Affairs and National Security"},
"R" => {1=>"Civil Rights, Social Action, Advocacy"},
"S" => {1=>"Community Improvement, Capacity Building"},
"T" => {1=>"Philanthropy, Voluntarism and Grantmaking Foundations"},
"U" => {1=>"Science and Technology Research Institutes, Services"},
"V" => {1=>"Social Science Research Institutes, Services"},
"W" => {1=>"Public, Society Benefit – Multipurpose and Other"},
"X" => {1=>"Religion-Related, Spiritual Development"},
"Y" => {1=>"Mutual/Membership Benefit Organizations, Other"},
"Z" => {1=>"Unknown"}
}

NTEE_CORE_CODES = Hash.new

{

#A Arts, Culture and Humanities
"A01" => "Alliance/Advocacy Organizations",
"A02" => "Management & Technical Assistance",
"A03" => "Professional Societies, Associations ",
"A05" => "Research Institutes and/or Public Policy Analysis",
"A11" => "Single Organization Support",
"A12" => "Fund Raising and/or Fund Distribution",
"A19" => "Nonmonetary Support N.E.C.",
"A20" => "Arts, Cultural Organizations - Multipurpose",
"A23" => "Cultural, Ethnic Awareness",
"A25" => "Arts Education",
"A26" => "Arts Council/Agency",
"A30" => "Media, Communications Organizations",
"A31" => "Film, Video",
"A32" => "Television",
"A33" => "Printing, Publishing",
"A34" => "Radio",
"A40" => "Visual Arts Organizations",
"A50" => "Museum, Museum Activities",
"A51" => "Art Museums",
"A52" => "Children's Museums",
"A54" => "History Museums",
"A56" => "Natural History, Natural Science Museums",
"A57" => "Science and Technology Museums",
"A60" => "Performing Arts Organizations",
"A61" => "Performing Arts Centers",
"A62" => "Dance",
"A63" => "Ballet",
"A65" => "Theater",
"A68" => "Music",
"A69" => "Symphony Orchestras",
"A6A" => "Opera",
"A6B" => "Singing, Choral",
"A6C" => "Music Groups, Bands, Ensembles",
"A6E" => "Performing Arts Schools",
"A70" => "Humanities Organizations	 ",
"A80" => "Historical Societies, Related Historical Activities",
"A84" => "Commemorative Events",
"A90" => "Arts Service Organizations and Activities",
"A99" => "Arts, Culture, and Humanities N.E.C.",

#B Education
"B01" => "Alliance/Advocacy Organizations",
"B02" => "Management & Technical Assistance",
"B03" => "Professional Societies, Associations",
"B05" => "Research Institutes and/or Public Policy Analysis",
"B11" => "Single Organization Support",
"B12" => "Fund Raising and/or Fund Distribution",
"B19" => "Nonmonetary Support N.E.C.",
"B20 " => "Elementary, Secondary Education, K - 12",
"B21" => "Kindergarten, Preschool, Nursery School, Early Admissions",
"B24" => "Primary, Elementary Schools",
"B25" => "Secondary, High School",
"B28" => "Specialized Education Institutions",
"B30" => "Vocational, Technical Schools",
"B40" => "Higher Education Institutions",
"B41" => "Community or Junior Colleges",
"B42" => "Undergraduate College (4-year)",
"B43" => "University or Technological Institute",
"B50" => "Graduate, Professional Schools (Separate Entities)",
"B60" => "Adult, Continuing Education",
"B70" => "Libraries",
"B80" => "Student Services, Organizations of Students",
"B82" => "Scholarships, Student Financial Aid Services, Awards",
"B83" => "Student Sororities, Fraternities",
"B84" => "Alumni Associations",
"B90" => "Educational Services and Schools - Other",
"B92" => "Remedial Reading, Reading Encouragement",
"B94" => "Parent/Teacher Group",
"B99" => "Education N.E.C.",

#C Environmental Quality, Protection and Beautification 
"C01" => "Alliance/Advocacy Organizations",
"C02" => "Management & Technical Assistance",
"C03" => "Professional Societies, Associations",
"C05" => "Research Institutes and/or Public Policy Analysis",
"C11" => "Single Organization Support",
"C12" => "Fund Raising and/or Fund Distribution",
"C19" => "Nonmonetary Support N.E.C.",
"C20" => "Pollution Abatement and Control Services",
"C27" => "Recycling Programs",
"C30" => "Natural Resources Conservation and Protection",
"C32" => "Water Resource, Wetlands Conservation and Management",
"C34" => "Land Resources Conservation",
"C35" => "Energy Resources Conservation and Development",
"C36" => "Forest Conservation",
"C40" => "Botanical, Horticultural, and Landscape Services",
"C41" => "Botanical Gardens, Arboreta and Botanical Organizations",
"C42" => "Garden Club, Horticultural Program",
"C50" => "Environmental Beautification and Aesthetics",
"C60" => "Environmental Education and Outdoor Survival Programs",
"C99" => "Environmental Quality, Protection, and Beautification N.E.C.",

#D Animal-Related 
"D01" => "Alliance/Advocacy Organizations",
"D02" => "Management & Technical Assistance",
"D03" => "Professional Societies, Associations",
"D05" => "Research Institutes and/or Public Policy Analysis",
"D11" => "Single Organization Support",
"D12" => "Fund Raising and/or Fund Distribution",
"D19" => "Nonmonetary Support N.E.C.",
"D20" => "Animal Protection and Welfare",
"D30" => "Wildlife Preservation, Protection",
"D31" => "Protection of Endangered Species",
"D32" => "Bird Sanctuary, Preserve",
"D33" => "Fisheries Resources",
"D34" => "Wildlife Sanctuary, Refuge",
"D40" => "Veterinary Services",
"D50" => "Zoo, Zoological Society",
"D60" => "Other Services - Specialty Animals",
"D61" => "Animal Training, Behavior",
"D99" => "Animal-Related N.E.C.",

#E Health - General and Rehabilitative
"E01" => "Alliance/Advocacy Organizations",
"E02" => "Management & Technical Assistance",
"E03" => "Professional Societies, Associations",
"E05" => "Research Institutes and/or Public Policy Analysis",
"E11" => "Single Organization Support",
"E12" => "Fund Raising and/or Fund Distribution",
"E19" => "Nonmonetary Support N.E.C.",
"E20" => "Hospitals and Related Primary Medical Care Facilities",
"E21" => "Community Health Systems",
"E22" => "Hospital, General",
"E24" => "Hospital, Specialty",
"E30" => "Health Treatment Facilities, Primarily Outpatient",
"E31" => "Group Health Practice (Health Maintenance Organizations)",
"E32" => "Ambulatory Health Center, Community Clinic",
"E40" => "Reproductive Health Care Facilities and Allied Services",
"E42" => "Family Planning Centers",
"E50" => "Rehabilitative Medical Services",
"E60" => "Health Support Services",
"E61" => "Blood Supply Related",
"E62" => "Ambulance, Emergency Medical Transport Services",
"E65" => "Organ and Tissue Banks",
"E70" => "Public Health Program (Includes General Health and Wellness Promotion Services)",
"E80" => "Health, General and Financing",
"E86" => "Patient Services - Entertainment, Recreation",
"E90" => "Nursing Services (General)",
"E91" => "Nursing, Convalescent Facilities",
"E92" => "Home Health Care",
"E99" => "Health - General and Rehabilitative N.E.C.",

#F Mental Health, Crisis Intervention
"F01" => "Alliance/Advocacy Organizations",
"F02" => "Management & Technical Assistance",
"F03" => "Professional Societies, Associations",
"F05" => "Research Institutes and/or Public Policy Analysis",
"F11" => "Single Organization Support",
"F12" => "Fund Raising and/or Fund Distribution",
"F19" => "Nonmonetary Support N.E.C.",
"F20" => "Alcohol, Drug and Substance Abuse, Dependency Prevention and Treatment",
"F21" => "Alcohol, Drug Abuse, Prevention Only",
"F22" => "Alcohol, Drug Abuse, Treatment Only",
"F30" => "Mental Health Treatment - Multipurpose and N.E.C.",
"F31" => "Psychiatric, Mental Health Hospital",
"F32" => "Community Mental Health Center",
"F33" => "Group Home, Residential Treatment Facility - Mental Health Related",
"F40" => "Hot Line, Crisis Intervention Services",
"F42" => "Rape Victim Services",
"F50" => "Addictive Disorders N.E.C.",
"F52" => "Smoking Addiction",
"F53" => "Eating Disorder, Addiction",
"F54" => "Gambling Addiction",
"F60" => "Counseling, Support Groups",
"F70" => "Mental Health Disorders",
"F80" => "Mental Health Association, Multipurpose",
"F99" => "Mental Health, Crisis Intervention N.E.C.",

#G Diseases, Disorders, Medical Disciplines
"G01" => "Alliance/Advocacy Organizations",
"G02" => "Management & Technical Assistance",
"G03" => "Professional Societies, Associations",
"G05" => "Research Institutes and/or Public Policy Analysis",
"G11" => "Single Organization Support",
"G12" => "Fund Raising and/or Fund Distribution",
"G19" => "Nonmonetary Support N.E.C.",
"G20" => "Birth Defects and Genetic Diseases",
"G25" => "Down Syndrome",
"G30" => "Cancer",
"G40" => "Diseases of Specific Organs",
"G41" => "Eye Diseases, Blindness and Vision Impairments",
"G42" => "Ear and Throat Diseases",
"G43" => "Heart and Circulatory System Diseases, Disorders",
"G44" => "Kidney Disease",
"G45" => "Lung Disease",
"G48" => "Brain Disorders",
"G50" => "Nerve, Muscle and Bone Diseases",
"G51" => "Arthritis",
"G54" => "Epilepsy",
"G60" => "Allergy Related Diseases",
"G61" => "Asthma",
"G70" => "Digestive Diseases, Disorders",
"G80" => "Specifically Named Diseases",
"G81" => "AIDS",
"G83" => "Alzheimer's Disease",
"G84" => "Autism",
"G90" => "Medical Disciplines",
"G92" => "Biomedicine, Bioengineering",
"G94" => "Geriatrics",
"G96" => "Neurology, Neuroscience",
"G98" => "Pediatrics",
"G9B" => "Surgery",
"G99" => "Diseases, Disorders, Medical Disciplines N.E.C.",

#H Medical Research
"H01" => "Alliance/Advocacy Organizations",
"H02" => "Management & Technical Assistance",
"H03" => "Professional Societies, Associations",
"H05" => "Research Institutes and/or Public Policy Analysis",
"H11" => "Single Organization Support",
"H12" => "Fund Raising and/or Fund Distribution",
"H19" => "Nonmonetary Support N.E.C.",
"H20" => "Birth Defects, Genetic Diseases Research",
"H25" => "Down Syndrome Research",
"H30" => "Cancer Research",
"H40" => "Specific Organ Research",
"H41" => "Eye Research",
"H42" => "Ear and Throat Research",
"H43" => "Heart, Circulatory Research",
"H44" => "Kidney Research",
"H45" => "Lung Research",
"H48" => "Brain Disorders Research",
"H50" => "Nerve, Muscle, Bone Research",
"H51" => "Arthritis Research",
"H54" => "Epilepsy Research",
"H60" => "Allergy Related Disease Research",
"H61" => "Asthma Research",
"H70" => "Digestive Disease, Disorder Research",
"H80" => "Specifically Named Diseases Research",
"H81" => "AIDS Research",
"H83" => "Alzheimer's Disease Research",
"H84" => "Autism Research",
"H90" => "Medical Specialty Research",
"H92" => "Biomedicine, Bioengineering Research",
"H94" => "Geriatrics Research",
"H96" => "Neurology, Neuroscience Research",
"H98" => "Pediatrics Research",
"H9B" => "Surgery Research",
"H99" => "Medical Research N.E.C.",

#I Crime, Legal-Related
"I01" => "Alliance/Advocacy Organizations",
"I02" => "Management & Technical Assistance",
"I03" => "Professional Societies, Associations",
"I05" => "Research Institutes and/or Public Policy Analysis",
"I11" => "Single Organization Support",
"I12" => "Fund Raising and/or Fund Distribution",
"I19" => "Nonmonetary Support N.E.C.",
"I20" => "Crime Prevention N.E.C.",
"I21" => "Delinquency Prevention",
"I23" => "Drunk Driving Related",
"I30" => "Correctional Facilities N.E.C.",
"I31" => "Transitional Care, Half-Way House for Offenders, Ex-Offenders",
"I40" => "Rehabilitation Services for Offenders",
"I43" => "Services to Prisoners and Families - Multipurpose",
"I44" => "Prison Alternatives",
"I50" => "Administration of Justice, Courts",
"I51" => "Dispute Resolution, Mediation Services",
"I60" => "Law Enforcement Agencies (Police Departments)",
"I70" => "Protection Against, Prevention of Neglect, Abuse, Exploitation",
"I71" => "Spouse Abuse, Prevention of",
"I72" => "Child Abuse, Prevention of",
"I73" => "Sexual Abuse, Prevention of",
"I80" => "Legal Services",
"I83" => "Public Interest Law, Litigation",
"I99" => "Crime, Legal Related N.E.C.",

#J Employment, Job-Related
"J01" => "Alliance/Advocacy Organizations",
"J02" => "Management & Technical Assistance",
"J03" => "Professional Societies, Associations",
"J05" => "Research Institutes and/or Public Policy Analysis",
"J11" => "Single Organization Support",
"J12" => "Fund Raising and/or Fund Distribution",
"J19" => "Nonmonetary Support N.E.C.",
"J20" => "Employment Procurement Assistance, Job Training",
"J21" => "Vocational Counseling, Guidance and Testing",
"J22" => "Vocational Training",
"J30" => "Vocational Rehabilitation",
"J32" => "Goodwill Industries",
"J33" => "Sheltered Remunerative Employment, Work Activity Center N.E.C.",
"J40" => "Labor Unions, Organizations",
"J99" => "Employment, Job Related N.E.C.",

#K Food, Agriculture and Nutrition 
"K01" => "Alliance/Advocacy Organizations",
"K02" => "Management & Technical Assistance",
"K03" => "Professional Societies, Associations",
"K05" => "Research Institutes and/or Public Policy Analysis",
"K11" => "Single Organization Support",
"K12" => "Fund Raising and/or Fund Distribution",
"K19" => "Nonmonetary Support N.E.C.",
"K20" => "Agricultural Programs",
"K25" => "Farmland Preservation",
"K26" => "Livestock Breeding, Development, Management",
"K28" => "Farm Bureau, Grange",
"K30" => "Food Service, Free Food Distribution Programs",
"K31" => "Food Banks, Food Pantries",
"K34" => "Congregate Meals",
"K35" => "Eatery, Agency, Organization Sponsored",
"K36" => "Meals on Wheels",
"K40" => "Nutrition Programs",
"K50" => "Home Economics",
"K99" => "Food, Agriculture, and Nutrition N.E.C.",

#L Housing, Shelter
"L01" => "Alliance/Advocacy Organizations",
"L02" => "Management & Technical Assistance",
"L03" => "Professional Societies, Associations",
"L05" => "Research Institutes and/or Public Policy Analysis",
"L11" => "Single Organization Support",
"L12" => "Fund Raising and/or Fund Distribution",
"L19" => "Nonmonetary Support N.E.C.",
"L20" => "Housing Development, Construction, Management",
"L21" => "Public Housing Facilities",
"L22" => "Senior Citizens' Housing/Retirement Communities",
"L25" => "Housing Rehabilitation",
"L30" => "Housing Search Assistance",
"L40" => "Low-Cost Temporary Housing",
"L41" => "Homeless, Temporary Shelter For",
"L50" => "Housing Owners, Renters Organizations",
"L80" => "Housing Support Services -- Other",
"L81" => "Home Improvement and Repairs",
"L82" => "Housing Expense Reduction Support",
"L99" => "Housing, Shelter N.E.C.",

#M Public Safety, Disaster Preparedness and Relief
"M01" => "Alliance/Advocacy Organizations",
"M02" => "Management & Technical Assistance",
"M03" => "Professional Societies, Associations",
"M05" => "Research Institutes and/or Public Policy Analysis",
"M11" => "Single Organization Support",
"M12" => "Fund Raising and/or Fund Distribution",
"M19" => "Nonmonetary Support N.E.C.",
"M20" => "Disaster Preparedness and Relief Services",
"M23" => "Search and Rescue Squads, Services",
"M24" => "Fire Prevention, Protection, Control",
"M40" => "Safety Education",
"M41" => "First Aid Training, Services",
"M42" => "Automotive Safety",
"M99" => "Public Safety, Disaster Preparedness, and Relief N.E.C.",

#N Recreation, Sports, Leisure, Athletics 
"N01" => "Alliance/Advocacy Organizations",
"N02" => "Management & Technical Assistance",
"N03" => "Professional Societies, Associations",
"N05" => "Research Institutes and/or Public Policy Analysis",
"N11" => "Single Organization Support",
"N12" => "Fund Raising and/or Fund Distribution",
"N19" => "Nonmonetary Support N.E.C.",
"N20" => "Recreational and Sporting Camps",
"N30" => "Physical Fitness and Community Recreational Facilities",
"N31" => "Community Recreational Centers",
"N32" => "Parks and Playgrounds",
"N40" => "Sports Training Facilities, Agencies",
"N50" => "Recreational, Pleasure, or Social Club",
"N52" => "Fairs, County and Other",
"N60" => "Amateur Sports Clubs, Leagues, N.E.C.",
"N61" => "Fishing, Hunting Clubs",
"N62" => "Basketball",
"N63" => "Baseball, Softball",
"N64" => "Soccer Clubs, Leagues",
"N65" => "Football Clubs, Leagues",
"N66" => "Tennis, Racquet Sports Clubs, Leagues",
"N67" => "Swimming, Water Recreation",
"N68" => "Winter Sports (Snow and Ice)",
"N69" => "Equestrian, Riding",
"N6A" => "Golf",
"N70" => "Amateur Sports Competitions",
"N71" => "Olympics Committees and Related International Competitions",
"N72" => "Special Olympics",
"N80" => "Professional Athletic Leagues",
"N99" => "Recreation, Sports, Leisure, Athletics N.E.C.",

#O Youth Development 
"O01" => "Alliance/Advocacy Organizations",
"O02" => "Management & Technical Assistance",
"O03" => "Professional Societies, Associations",
"O05" => "Research Institutes and/or Public Policy Analysis",
"O11" => "Single Organization Support",
"O12" => "Fund Raising and/or Fund Distribution",
"O19" => "Nonmonetary Support N.E.C.",
"O20" => "Youth Centers, Clubs, Multipurpose",
"O21" => "Boys Clubs",
"O22" => "Girls Clubs",
"O23" => "Boys and Girls Clubs (Combined)",
"O30" => "Adult, Child Matching Programs",
"O31" => "Big Brothers, Big Sisters",
"O40" => "Scouting Organizations",
"O41" => "Boy Scouts of America",
"O42" => "Girl Scouts of the U.S.A.",
"O43" => "Camp Fire",
"O50" => "Youth Development Programs, Other",
"O51" => "Youth Community Service Clubs",
"O52" => "Youth Development - Agricultural",
"O53" => "Youth Development - Business",
"O54" => "Youth Development - Citizenship Programs",
"O55" => "Youth Development - Religious Leadership",
"O99" => "Youth Development N.E.C.",

#P Human Services - Multipurpose and Other 
"P01" => "Alliance/Advocacy Organizations",
"P02" => "Management & Technical Assistance",
"P03" => "Professional Societies, Associations",
"P05" => "Research Institutes and/or Public Policy Analysis",
"P11" => "Single Organization Support",
"P12" => "Fund Raising and/or Fund Distribution",
"P19" => "Nonmonetary Support N.E.C.",
"P20" => "Human Service Organizations - Multipurpose",
"P21" => "American Red Cross",
"P22" => "Urban League",
"P24" => "Salvation Army",
"P26" => "Volunteers of America",
"P27" => "Young Men's or Women's Associations (YMCA, YWCA, YWHA, YMHA)",
"P28" => "Neighborhood Centers, Settlement Houses",
"P29" => "Thrift Shops",
"P30" => "Children's, Youth Services",
"P31" => "Adoption",
"P32" => "Foster Care",
"P33" => "Child Day Care",
"P40" => "Family Services",
"P42" => "Single Parent Agencies, Services",
"P43" => "Family Violence Shelters, Services",
"P44" => "Homemaker, Home Health Aide",
"P45" => "Family Services, Adolescent Parents",
"P46" => "Family Counseling",
"P50" => "Personal Social Services",
"P51" => "Financial Counseling, Money Management",
"P52" => "Transportation, Free or Subsidized",
"P58" => "Gift Distribution",
"P60" => "Emergency Assistance (Food, Clothing, Cash)",
"P61" => "Travelers' Aid",
"P62" => "Victims' Services",
"P70" => "Residential, Custodial Care",
"P72" => "Half-Way House (Short-Term Residential Care)",
"P73" => "Group Home (Long Term)",
"P74" => "Hospice",
"P75" => "Senior Continuing Care Communities",
"P80" => "Services to Promote the Independence of Specific Populations",
"P81" => "Senior Centers, Services",
"P82" => "Developmentally Disabled Centers, Services",
"P84" => "Ethnic, Immigrant Centers, Services",
"P85" => "Homeless Persons Centers, Services",
"P86" => "Blind/Visually Impaired Centers, Services",
"P87" => "Deaf/Hearing Impaired Centers, Services",
"P99" => "Human Services - Multipurpose and Other N.E.C.",

#Q International, Foreign Affairs and National Security 
"Q01" => "Alliance/Advocacy Organizations",
"Q02" => "Management & Technical Assistance",
"Q03" => "Professional Societies, Associations",
"Q05" => "Research Institutes and/or Public Policy Analysis",
"Q11" => "Single Organization Support",
"Q12" => "Fund Raising and/or Fund Distribution",
"Q19" => "Nonmonetary Support N.E.C.",
"Q20" => "Promotion of International Understanding",
"Q21" => "International Cultural Exchange",
"Q22" => "International Student Exchange and Aid",
"Q23" => "International Exchanges, N.E.C.",
"Q30" => "International Development, Relief Services",
"Q31" => "International Agricultural Development",
"Q32" => "International Economic Development",
"Q33" => "International Relief",
"Q40" => "International Peace and Security",
"Q41" => "Arms Control, Peace Organizations",
"Q42" => "United Nations Association",
"Q43" => "National Security, Domestic",
"Q70" => "International Human Rights",
"Q71" => "International Migration, Refugee Issues",
"Q99" => "International, Foreign Affairs, and National Security N.E.C.",

#R Civil Rights, Social Action, Advocacy 
"R01" => "Alliance/Advocacy Organizations",
"R02" => "Management & Technical Assistance",
"R03" => "Professional Societies, Associations",
"R05" => "Research Institutes and/or Public Policy Analysis",
"R11" => "Single Organization Support",
"R12" => "Fund Raising and/or Fund Distribution",
"R19" => "Nonmonetary Support N.E.C.",
"R20" => "Civil Rights, Advocacy for Specific Groups",
"R22" => "Minority Rights",
"R23" => "Disabled Persons' Rights",
"R24" => "Women's Rights",
"R25" => "Seniors' Rights",
"R26" => "Lesbian, Gay Rights",
"R30" => "Intergroup, Race Relations",
"R40" => "Voter Education, Registration",
"R60" => "Civil Liberties Advocacy",
"R61" => "Reproductive Rights",
"R62" => "Right to Life",
"R63" => "Censorship, Freedom of Speech and Press Issues",
"R67" => "Right to Die, Euthanasia Issues",
"R99" => "Civil Rights, Social Action, Advocacy N.E.C.",

#S Community Improvement, Capacity Building 
"S01" => "Alliance/Advocacy Organizations",
"S02" => "Management & Technical Assistance",
"S03" => "Professional Societies, Associations",
"S05" => "Research Institutes and/or Public Policy Analysis",
"S11" => "Single Organization Support",
"S12" => "Fund Raising and/or Fund Distribution",
"S19" => "Nonmonetary Support N.E.C.",
"S20" => "Community, Neighborhood Development, Improvement (General)",
"S21" => "Community Coalitions",
"S22" => "Neighborhood, Block Associations",
"S30" => "Economic Development",
"S31" => "Urban, Community Economic Development",
"S32" => "Rural Development",
"S40" => "Business and Industry",
"S41" => "Promotion of Business",
"S43" => "Management Services for Small Business, Entrepreneurs",
"S46" => "Boards of Trade",
"S47" => "Real Estate Organizations",
"S50" => "Nonprofit Management",
"S80" => "Community Service Clubs",
"S81" => "Women's Service Clubs",
"S82" => "Men's Service Clubs",
"S99" => "Community Improvement, Capacity Building N.E.C.",

#T Philanthropy, Voluntarism and Grantmaking Foundations 
"T01" => "Alliance/Advocacy Organizations",
"T02" => "Management & Technical Assistance",
"T03" => "Professional Societies, Associations",
"T05" => "Research Institutes and/or Public Policy Analysis",
"T11" => "Single Organization Support",
"T12" => "Fund Raising and/or Fund Distribution",
"T19" => "Nonmonetary Support N.E.C.",
"T20" => "Private Grantmaking Foundations",
"T21" => "Corporate Foundations",
"T22" => "Private Independent Foundations",
"T23" => "Private Operating Foundations",
"T30" => "Public Foundations",
"T31" => "Community Foundations",
"T40" => "Voluntarism Promotion",
"T50" => "Philanthropy, Charity, Voluntarism Promotion, General",
"T70" => "Fund Raising Organizations That Cross Categories",
"T90" => "Named Trusts/Foundations N.E.C.",
"T99" => "Philanthropy, Voluntarism, and Grantmaking Foundations N.E.C.",

#U Science and Technology Research Institutes, Services 
"U01" => "Alliance/Advocacy Organizations",
"U02" => "Management & Technical Assistance",
"U03" => "Professional Societies, Associations",
"U05" => "Research Institutes and/or Public Policy Analysis",
"U11" => "Single Organization Support",
"U12" => "Fund Raising and/or Fund Distribution",
"U19" => "Nonmonetary Support N.E.C.",
"U20" => "Science, General",
"U21" => "Marine Science and Oceanography",
"U30" => "Physical Sciences, Earth Sciences Research and Promotion",
"U31" => "Astronomy",
"U33" => "Chemistry, Chemical Engineering",
"U34" => "Mathematics",
"U36" => "Geology",
"U40" => "Engineering and Technology Research, Services",
"U41" => "Computer Science",
"U42" => "Engineering",
"U50" => "Biological, Life Science Research",
"U99" => "Science and Technology Research Institutes, Services N.E.C.",

#V Social Science Research Institutes, Services
"V01" => "Alliance/Advocacy Organizations",
"V02" => "Management & Technical Assistance",
"V03" => "Professional Societies, Associations",
"V05" => "Research Institutes and/or Public Policy Analysis",
"V11" => "Single Organization Support",
"V12" => "Fund Raising and/or Fund Distribution",
"V19" => "Nonmonetary Support N.E.C.",
"V20" => "Social Science Institutes, Services",
"V21" => "Anthropology, Sociology",
"V22" => "Economics (as a social science)",
"V23" => "Behavioral Science",
"V24" => "Political Science",
"V25" => "Population Studies",
"V26" => "Law, International Law, Jurisprudence",
"V30" => "Interdisciplinary Research",
"V31" => "Black Studies",
"V32" => "Women's Studies",
"V33" => "Ethnic Studies",
"V34" => "Urban Studies",
"V35" => "International Studies",
"V36" => "Gerontology (as a social science)",
"V37" => "Labor Studies",
"V99" => "Social Science Research Institutes, Services N.E.C.",

#W Public, Society Benefit - Multipurpose and Other
"W01" => "Alliance/Advocacy Organizations",
"W02" => "Management & Technical Assistance",
"W03" => "Professional Societies, Associations",
"W05" => "Research Institutes and/or Public Policy Analysis",
"W11" => "Single Organization Support",
"W12" => "Fund Raising and/or Fund Distribution",
"W19" => "Nonmonetary Support N.E.C.",
"W20" => "Government and Public Administration",
"W22" => "Public Finance, Taxation, Monetary Policy",
"W24" => "Citizen Participation",
"W30" => "Military, Veterans' Organizations",
"W40" => "Public Transportation Systems, Services",
"W50" => "Telephone, Telegraph and Telecommunication Services",
"W60" => "Financial Institutions, Services (Non-Government Related)",
"W61" => "Credit Unions",
"W70" => "Leadership Development",
"W80" => "Public Utilities",
"W90" => "Consumer Protection, Safety",
"W99" => "Public, Society Benefit - Multipurpose and Other N.E.C.",

#X Religion-Related, Spiritual Development 
"X01" => "Alliance/Advocacy Organizations",
"X02" => "Management & Technical Assistance",
"X03" => "Professional Societies, Associations",
"X05" => "Research Institutes and/or Public Policy Analysis",
"X11" => "Single Organization Support",
"X12" => "Fund Raising and/or Fund Distribution",
"X19" => "Nonmonetary Support N.E.C.",
"X20" => "Christian",
"X21" => "Protestant",
"X22" => "Roman Catholic",
"X30" => "Jewish",
"X40" => "Islamic",
"X50" => "Buddhist",
"X70" => "Hindu",
"X80" => "Religious Media, Communications Organizations",
"X81" => "Religious Film, Video",
"X82" => "Religious Television",
"X83" => "Religious Printing, Publishing",
"X84" => "Religious Radio",
"X90" => "Interfaith Issues",
"X99" => "Religion Related, Spiritual Development N.E.C.",

#Y Mutual/Membership Benefit Organizations, Other 
"Y01" => "Alliance/Advocacy Organizations",
"Y02" => "Management & Technical Assistance",
"Y03" => "Professional Societies, Associations",
"Y05" => "Research Institutes and/or Public Policy Analysis",
"Y11" => "Single Organization Support",
"Y12" => "Fund Raising and/or Fund Distribution",
"Y19" => "Nonmonetary Support N.E.C.",
"Y20" => "Insurance Providers, Services",
"Y22" => "Local Benevolent Life Insurance Associations, Mutual Irrigation and Telephone Companies, and Like Organizations",
"Y23" => "Mutual Insurance Company or Association",
"Y24" => "Supplemental Unemployment Compensation",
"Y25" => "State-Sponsored Worker's Compensation Reinsurance Organizations",
"Y30" => "Pension and Retirement Funds",
"Y33" => "Teachers Retirement Fund Association",
"Y34" => "Employee Funded Pension Trust",
"Y35" => "Multi-Employer Pension Plans",
"Y40" => "Fraternal Beneficiary Societies",
"Y42" => "Domestic Fraternal Societies",
"Y43" => "Voluntary Employees Beneficiary Associations (Non-Government)",
"Y44" => "Voluntary Employees Beneficiary Associations (Government)",
"Y50" => "Cemeteries, Burial Services",
"Y99" => "Mutual/Membership Benefit Organizations, Other N.E.C.",

#Z Unknown
"Z99" => "Unknown"


}
