=begin
class Charity
#may not need following line if we don’t use datamapper, which makes a certain amount of sense
#include DataMapper::Resource 

include Neo4j::NodeMixin

#property :node_id,    Integer    # generated by neo4j

	property :name, :ein, :type => String, :index => :exact    # A varchar type string, for short strings
	property :address, :city, :state, :zip, :ntee_core_code, :ntee_common_code, :type => String

	has_n(:packages)

# Instantiate with:   Neo4j::Transaction.run do Person.new(:name => 'jimmy', :age => 35) end
end

end
=end
